# Generated by Django 3.2.8 on 2021-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('uu_menu_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('delivery_method', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('customer_addres', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('menu_orders', models.TextField(blank=True, default='', null=True)),
                ('sub_total', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('sales_tax_838', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('delivery_fee', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('tip', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('total', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('delivery_fee_tax_838', models.FloatField(blank=True, default=0, max_length=200, null=True)),
                ('date_object', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Date_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_object', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
